/**
 * Knowledge Capture Skill
 *
 * Captures decisions, patterns, and learnings from development work.
 * Generates ADRs, maintains pattern library, and supports retrospectives.
 */

class KnowledgeCapture {
  constructor(config = {}) {
    this.config = {
      decisionsDir: config.decisionsDir || 'maestro/decisions',
      patternsDir: config.patternsDir || 'maestro/patterns',
      retrospectivesDir: config.retrospectivesDir || 'maestro/retrospectives',
      autoCapture: config.autoCapture !== false,
      ...config
    };

    this.decisions = [];
    this.patterns = [];
  }

  /**
   * Create an Architecture Decision Record
   * @param {Object} decision - Decision details
   * @returns {Object} Created ADR
   */
  createADR(decision) {
    const adrId = this.generateADRId();
    const timestamp = new Date().toISOString();

    const adr = {
      id: adrId,
      title: decision.title,
      status: decision.status || 'proposed', // proposed, accepted, deprecated, superseded
      date: timestamp,
      context: decision.context,
      decision: decision.decision,
      consequences: decision.consequences || [],
      alternatives: decision.alternatives || [],
      relatedTracks: decision.trackIds || [],
      participants: decision.participants || [],
      supersedes: decision.supersedes || null,
      supersededBy: null,
      tags: decision.tags || [],
      metadata: {
        createdAt: timestamp,
        updatedAt: timestamp,
        autoGenerated: decision.autoGenerated || false
      }
    };

    this.decisions.push(adr);

    return {
      adr,
      filePath: `${this.config.decisionsDir}/${adrId}.md`,
      content: this.formatADRMarkdown(adr)
    };
  }

  /**
   * Auto-generate ADR from conversation analysis
   * @param {Object} conversation - Analyzed conversation
   * @returns {Object|null} Generated ADR or null
   */
  autoGenerateADR(conversation) {
    // Check if conversation contains a significant decision
    if (!this.isSignificantDecision(conversation)) {
      return null;
    }

    const extracted = {
      title: this.extractDecisionTitle(conversation),
      context: this.extractContext(conversation),
      decision: this.extractDecision(conversation),
      alternatives: this.extractAlternatives(conversation),
      consequences: this.extractConsequences(conversation),
      trackIds: conversation.relatedTracks || [],
      autoGenerated: true,
      tags: this.extractTags(conversation)
    };

    return this.createADR(extracted);
  }

  /**
   * Record a reusable pattern from implementation
   * @param {Object} pattern - Pattern details
   * @returns {Object} Created pattern
   */
  recordPattern(pattern) {
    const patternId = this.generatePatternId(pattern.name);
    const timestamp = new Date().toISOString();

    const record = {
      id: patternId,
      name: pattern.name,
      category: pattern.category, // architectural, design, implementation, testing
      description: pattern.description,
      problem: pattern.problem,
      solution: pattern.solution,
      codeExample: pattern.codeExample || null,
      useCases: pattern.useCases || [],
      tradeoffs: pattern.tradeoffs || [],
      relatedPatterns: pattern.relatedPatterns || [],
      sourceTrack: pattern.trackId || null,
      tags: pattern.tags || [],
      metadata: {
        createdAt: timestamp,
        usageCount: 0,
        lastUsed: null
      }
    };

    this.patterns.push(record);

    return {
      pattern: record,
      filePath: `${this.config.patternsDir}/${patternId}.md`,
      content: this.formatPatternMarkdown(record)
    };
  }

  /**
   * Extract patterns from completed track
   * @param {Object} track - Completed track data
   * @returns {Array} Extracted patterns
   */
  extractPatternsFromTrack(track) {
    const patterns = [];

    // Analyze implementation approach
    if (track.plan && track.plan.phases) {
      for (const phase of track.plan.phases) {
        const phasePattern = this.analyzePhaseForPatterns(phase);
        if (phasePattern) {
          patterns.push(phasePattern);
        }
      }
    }

    // Analyze code changes for common patterns
    if (track.commits) {
      const codePatterns = this.analyzeCommitsForPatterns(track.commits);
      patterns.push(...codePatterns);
    }

    return patterns;
  }

  /**
   * Create track retrospective
   * @param {Object} track - Completed track
   * @param {Object} feedback - Retrospective feedback
   * @returns {Object} Retrospective document
   */
  createRetrospective(track, feedback = {}) {
    const retroId = `retro-${track.id}`;
    const timestamp = new Date().toISOString();

    const retrospective = {
      id: retroId,
      trackId: track.id,
      trackTitle: track.title,
      completedAt: timestamp,
      duration: this.calculateTrackDuration(track),
      summary: {
        phasesCompleted: track.phases?.completed || 0,
        tasksCompleted: track.tasks?.completed || 0,
        totalCommits: track.commits?.length || 0
      },
      whatWentWell: feedback.whatWentWell || [],
      whatCouldImprove: feedback.whatCouldImprove || [],
      actionItems: feedback.actionItems || [],
      lessonsLearned: feedback.lessonsLearned || [],
      agentPerformance: this.summarizeAgentPerformance(track),
      metrics: {
        estimatedComplexity: track.plan?.complexity || 'unknown',
        actualDuration: this.calculateTrackDuration(track),
        iterationCount: this.countIterations(track),
        qualityGatesPassed: feedback.qualityGatesPassed || true
      },
      recommendations: this.generateRetrospectiveRecommendations(track, feedback)
    };

    return {
      retrospective,
      filePath: `${this.config.retrospectivesDir}/${retroId}.md`,
      content: this.formatRetrospectiveMarkdown(retrospective)
    };
  }

  /**
   * Generate retrospective prompts for track completion
   * @param {Object} track - Completed track
   * @returns {Array} Prompts for user reflection
   */
  generateRetrospectivePrompts(track) {
    const prompts = [
      {
        id: 'went_well',
        question: 'What went well during this track implementation?',
        category: 'positive',
        suggestions: [
          'Good agent collaboration',
          'Clear requirements',
          'Smooth phase transitions',
          'Effective testing'
        ]
      },
      {
        id: 'could_improve',
        question: 'What could have been improved?',
        category: 'improvement',
        suggestions: [
          'Requirements clarity',
          'Estimation accuracy',
          'Agent selection',
          'Testing coverage'
        ]
      },
      {
        id: 'lessons',
        question: 'What key lessons were learned?',
        category: 'learning',
        suggestions: []
      },
      {
        id: 'actions',
        question: 'What action items should we take forward?',
        category: 'action',
        suggestions: [
          'Update coding standards',
          'Add to pattern library',
          'Create documentation',
          'Refine workflow'
        ]
      }
    ];

    // Add track-specific prompts
    if (track.blockers && track.blockers.length > 0) {
      prompts.push({
        id: 'blockers_resolution',
        question: 'How were blockers resolved? Any prevention strategies?',
        category: 'improvement',
        context: track.blockers
      });
    }

    return prompts;
  }

  /**
   * Search patterns by criteria
   * @param {Object} query - Search criteria
   * @returns {Array} Matching patterns
   */
  searchPatterns(query) {
    let results = [...this.patterns];

    if (query.category) {
      results = results.filter(p => p.category === query.category);
    }

    if (query.tags && query.tags.length > 0) {
      results = results.filter(p =>
        query.tags.some(tag => p.tags.includes(tag))
      );
    }

    if (query.keyword) {
      const keyword = query.keyword.toLowerCase();
      results = results.filter(p =>
        p.name.toLowerCase().includes(keyword) ||
        p.description.toLowerCase().includes(keyword) ||
        p.problem.toLowerCase().includes(keyword)
      );
    }

    return results.sort((a, b) =>
      b.metadata.usageCount - a.metadata.usageCount
    );
  }

  /**
   * Find relevant decisions for a track
   * @param {Object} track - Track to find decisions for
   * @returns {Array} Related decisions
   */
  findRelatedDecisions(track) {
    return this.decisions.filter(d =>
      d.relatedTracks.includes(track.id) ||
      d.tags.some(tag => track.tags?.includes(tag))
    );
  }

  // Format methods
  formatADRMarkdown(adr) {
    const statusIcon = {
      proposed: 'Proposed',
      accepted: 'Accepted',
      deprecated: 'Deprecated',
      superseded: 'Superseded'
    }[adr.status] || adr.status;

    let content = `# ADR-${adr.id}: ${adr.title}

**Status**: ${statusIcon}
**Date**: ${adr.date}
**Tags**: ${adr.tags?.join(', ') || 'none'}
`;

    // Add review information if present
    if (adr.reviewDate) {
      const reviewDue = new Date(adr.reviewDate) <= new Date() ? ' (OVERDUE)' : '';
      content += `**Review Date**: ${adr.reviewDate}${reviewDue}
`;
      if (adr.reviewReason) {
        content += `**Review Reason**: ${adr.reviewReason}
`;
      }
    }

    // Add supersession warning if superseded
    if (adr.status === 'superseded' && adr.supersededBy) {
      content += `
> **This decision has been superseded by [${adr.supersededBy}]**
`;
    }

    content += `
## Context

${adr.context}

## Decision

${adr.decision}

## Alternatives Considered

${adr.alternatives?.map((alt, i) => `${i + 1}. **${alt.title}**: ${alt.description}
   - Pros: ${alt.pros?.join(', ') || 'N/A'}
   - Cons: ${alt.cons?.join(', ') || 'N/A'}`).join('\n\n') || 'None documented'}

## Consequences

### Positive
${adr.consequences?.filter(c => c.type === 'positive').map(c => `- ${c.description}`).join('\n') || '- None documented'}

### Negative
${adr.consequences?.filter(c => c.type === 'negative').map(c => `- ${c.description}`).join('\n') || '- None documented'}

### Neutral
${adr.consequences?.filter(c => c.type === 'neutral').map(c => `- ${c.description}`).join('\n') || '- None documented'}

## Related

- **Tracks**: ${adr.relatedTracks?.join(', ') || 'None'}
`;

    // Add supersession chain information
    if (adr.supersedes && adr.supersedes.length > 0) {
      content += `- **Supersedes**: ${adr.supersedes.join(', ')}
`;
    }
    if (adr.supersededBy) {
      content += `- **Superseded By**: ${adr.supersededBy}
`;
    }

    content += `- **Participants**: ${adr.participants?.join(', ') || 'Not recorded'}

---
*Auto-generated: ${adr.metadata?.autoGenerated || false}*
*Created: ${adr.metadata?.createdAt || adr.date}*
${adr.metadata?.updatedAt ? `*Updated: ${adr.metadata.updatedAt}*` : ''}
`;

    return content;
  }

  formatPatternMarkdown(pattern) {
    return `# Pattern: ${pattern.name}

**Category**: ${pattern.category}
**ID**: ${pattern.id}
**Tags**: ${pattern.tags.join(', ') || 'none'}

## Problem

${pattern.problem}

## Solution

${pattern.solution}

${pattern.codeExample ? `## Code Example

\`\`\`
${pattern.codeExample}
\`\`\`` : ''}

## Use Cases

${pattern.useCases.map(uc => `- ${uc}`).join('\n') || 'Not documented'}

## Trade-offs

${pattern.tradeoffs.map(t => `- **${t.aspect}**: ${t.description}`).join('\n') || 'Not documented'}

## Related Patterns

${pattern.relatedPatterns.map(rp => `- ${rp}`).join('\n') || 'None'}

---
*Source Track: ${pattern.sourceTrack || 'N/A'}*
*Usage Count: ${pattern.metadata.usageCount}*
`;
  }

  formatRetrospectiveMarkdown(retro) {
    return `# Retrospective: ${retro.trackTitle}

**Track ID**: ${retro.trackId}
**Completed**: ${retro.completedAt}
**Duration**: ${retro.duration}

## Summary

| Metric | Value |
|--------|-------|
| Phases Completed | ${retro.summary.phasesCompleted} |
| Tasks Completed | ${retro.summary.tasksCompleted} |
| Total Commits | ${retro.summary.totalCommits} |

## What Went Well

${retro.whatWentWell.map(item => `- ${item}`).join('\n') || '- Nothing recorded'}

## What Could Improve

${retro.whatCouldImprove.map(item => `- ${item}`).join('\n') || '- Nothing recorded'}

## Lessons Learned

${retro.lessonsLearned.map(item => `- ${item}`).join('\n') || '- Nothing recorded'}

## Action Items

${retro.actionItems.map((item, i) => `${i + 1}. ${item}`).join('\n') || 'No action items'}

## Agent Performance

${Object.entries(retro.agentPerformance).map(([agent, perf]) =>
    `- **${agent}**: ${perf.tasksCompleted} tasks, ${perf.rating || 'N/A'} rating`
  ).join('\n') || 'Not tracked'}

## Recommendations

${retro.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n') || 'None'}

---
*Generated: ${retro.completedAt}*
`;
  }

  // Helper methods
  generateADRId() {
    const count = this.decisions.length + 1;
    return String(count).padStart(4, '0');
  }

  generatePatternId(name) {
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return `${slug}-${Date.now().toString(36).slice(-4)}`;
  }

  isSignificantDecision(conversation) {
    const keywords = ['decided', 'chose', 'selected', 'will use', 'going with', 'prefer'];
    return keywords.some(kw => conversation.content?.toLowerCase().includes(kw));
  }

  extractDecisionTitle(conversation) {
    return 'Untitled Decision';
  }

  extractContext(conversation) {
    return conversation.context || 'Context not captured';
  }

  extractDecision(conversation) {
    return conversation.decision || 'Decision not captured';
  }

  extractAlternatives(conversation) {
    return [];
  }

  extractConsequences(conversation) {
    return [];
  }

  extractTags(conversation) {
    return [];
  }

  analyzePhaseForPatterns(phase) {
    return null;
  }

  analyzeCommitsForPatterns(commits) {
    return [];
  }

  calculateTrackDuration(track) {
    if (track.created && track.updated) {
      const start = new Date(track.created);
      const end = new Date(track.updated);
      const hours = Math.round((end - start) / (1000 * 60 * 60));
      return hours > 24 ? `${Math.round(hours / 24)} days` : `${hours} hours`;
    }
    return 'Unknown';
  }

  summarizeAgentPerformance(track) {
    const performance = {};
    // Would analyze agent contributions from track data
    return performance;
  }

  countIterations(track) {
    return track.notes?.length || 0;
  }

  generateRetrospectiveRecommendations(track, feedback) {
    const recommendations = [];

    if (feedback.whatCouldImprove?.length > 0) {
      recommendations.push('Address improvement areas in next similar track');
    }

    if (track.blockers?.length > 0) {
      recommendations.push('Document blocker prevention strategies');
    }

    return recommendations;
  }

  // ============================================
  // Real-time Capture Methods
  // ============================================

  /**
   * Capture a decision in real-time during execution
   * @param {Object} decision - Decision data from agent execution
   * @returns {Object} Captured decision with metadata
   */
  captureDecisionRealtime(decision) {
    const timestamp = new Date().toISOString();

    const captured = {
      id: this.generateRealtimeId('dec'),
      type: 'decision',
      timestamp: timestamp,
      title: decision.title || decision.summary,
      summary: decision.summary || decision.title,
      status: decision.status || 'accepted', // proposed, accepted, deprecated, superseded
      content: {
        choice: decision.choice || decision.decision,
        rationale: decision.rationale,
        alternatives: decision.alternatives || [],
        consequences: decision.consequences || [],
        tradeoffs: decision.tradeoffs || null,
        reversible: decision.reversible !== false
      },
      context: {
        trackId: decision.trackId,
        taskId: decision.taskId,
        phase: decision.phase,
        agentId: decision.agentId,
        branch: decision.branch
      },
      domain: decision.domain || this.inferDomainFromDecision(decision),
      tags: decision.tags || this.extractTagsFromDecision(decision),
      confidence: decision.confidence || 0.7,
      importance: decision.importance || 'normal',
      // Review tracking
      reviewDate: decision.reviewDate || null,
      reviewReason: decision.reviewReason || null,
      // Supersession tracking
      supersedes: decision.supersedes || [], // IDs of decisions this replaces
      supersededBy: decision.supersededBy || null, // ID of newer decision that replaces this
      metadata: {
        createdAt: timestamp,
        updatedAt: timestamp,
        source: 'realtime',
        autoExtracted: decision.autoExtracted || false,
        agentOutput: decision.agentOutput ? true : false
      }
    };

    // Add to in-memory collection for session
    this.decisions.push(captured);

    return {
      success: true,
      decision: captured,
      message: `Decision captured: ${captured.title}`
    };
  }

  /**
   * Mark a decision as superseded by a newer decision
   * @param {string} oldDecisionId - ID of decision being superseded
   * @param {string} newDecisionId - ID of the new decision
   * @param {Object} knowledgeStore - KnowledgeStore instance
   * @param {string} branch - Branch name
   * @returns {Object} Update result
   */
  supersedeDecision(oldDecisionId, newDecisionId, knowledgeStore, branch = null) {
    // Update the old decision
    const oldResult = knowledgeStore.update(oldDecisionId, {
      status: 'superseded',
      supersededBy: newDecisionId,
      metadata: {
        updatedAt: new Date().toISOString()
      }
    }, branch);

    if (!oldResult.success) {
      return {
        success: false,
        error: oldResult.error,
        message: `Failed to mark decision as superseded: ${oldResult.message}`
      };
    }

    // Update the new decision to reference what it supersedes
    const newDecision = knowledgeStore.get(newDecisionId, branch);
    if (newDecision) {
      const supersedes = newDecision.supersedes || [];
      if (!supersedes.includes(oldDecisionId)) {
        supersedes.push(oldDecisionId);
        knowledgeStore.update(newDecisionId, {
          supersedes: supersedes
        }, branch);
      }
    }

    return {
      success: true,
      oldDecisionId: oldDecisionId,
      newDecisionId: newDecisionId,
      message: `Decision ${oldDecisionId} marked as superseded by ${newDecisionId}`
    };
  }

  /**
   * Set a review date for a decision
   * @param {string} decisionId - Decision ID
   * @param {string} reviewDate - Date string (YYYY-MM-DD)
   * @param {string} reviewReason - Reason for review
   * @param {Object} knowledgeStore - KnowledgeStore instance
   * @param {string} branch - Branch name
   * @returns {Object} Update result
   */
  setDecisionReviewDate(decisionId, reviewDate, reviewReason, knowledgeStore, branch = null) {
    const result = knowledgeStore.update(decisionId, {
      reviewDate: reviewDate,
      reviewReason: reviewReason,
      metadata: {
        updatedAt: new Date().toISOString()
      }
    }, branch);

    if (!result.success) {
      return {
        success: false,
        error: result.error,
        message: `Failed to set review date: ${result.message}`
      };
    }

    return {
      success: true,
      decisionId: decisionId,
      reviewDate: reviewDate,
      reviewReason: reviewReason,
      message: `Review date set for decision ${decisionId}: ${reviewDate}`
    };
  }

  /**
   * Get decisions that need review (review date has passed)
   * @param {Object} knowledgeStore - KnowledgeStore instance
   * @param {string} branch - Branch name
   * @returns {Object} Decisions needing review
   */
  getDecisionsNeedingReview(knowledgeStore, branch = null) {
    const result = knowledgeStore.query({
      type: 'decision',
      fullEntries: true
    }, branch);

    if (!result.success) {
      return {
        success: false,
        decisions: [],
        message: `Failed to query decisions: ${result.message}`
      };
    }

    const now = new Date();
    const needsReview = (result.entries || []).filter(d => {
      if (!d.reviewDate) return false;
      if (d.status === 'superseded' || d.status === 'deprecated') return false;
      return new Date(d.reviewDate) <= now;
    });

    // Sort by review date (oldest first)
    needsReview.sort((a, b) => new Date(a.reviewDate) - new Date(b.reviewDate));

    return {
      success: true,
      decisions: needsReview,
      total: needsReview.length,
      message: `Found ${needsReview.length} decisions needing review`
    };
  }

  /**
   * Get the supersession chain for a decision
   * @param {string} decisionId - Decision ID
   * @param {Object} knowledgeStore - KnowledgeStore instance
   * @param {string} branch - Branch name
   * @returns {Object} Supersession chain
   */
  getSupersessionChain(decisionId, knowledgeStore, branch = null) {
    const chain = {
      ancestors: [], // Decisions this supersedes (going back)
      current: null,
      successors: [] // Decisions that supersede this (going forward)
    };

    const current = knowledgeStore.get(decisionId, branch);
    if (!current) {
      return {
        success: false,
        chain: chain,
        message: `Decision not found: ${decisionId}`
      };
    }

    chain.current = {
      id: current.id,
      title: current.title,
      status: current.status,
      createdAt: current.metadata?.createdAt
    };

    // Get ancestors (what this decision supersedes)
    const getAncestors = (ids) => {
      for (const id of ids || []) {
        const ancestor = knowledgeStore.get(id, branch);
        if (ancestor) {
          chain.ancestors.push({
            id: ancestor.id,
            title: ancestor.title,
            status: ancestor.status,
            createdAt: ancestor.metadata?.createdAt
          });
          // Recursively get older ancestors
          getAncestors(ancestor.supersedes);
        }
      }
    };
    getAncestors(current.supersedes);

    // Get successors (what supersedes this decision)
    const getSuccessors = (id) => {
      const decision = knowledgeStore.get(id, branch);
      if (decision && decision.supersededBy) {
        const successor = knowledgeStore.get(decision.supersededBy, branch);
        if (successor) {
          chain.successors.push({
            id: successor.id,
            title: successor.title,
            status: successor.status,
            createdAt: successor.metadata?.createdAt
          });
          // Recursively get newer successors
          getSuccessors(successor.id);
        }
      }
    };
    getSuccessors(decisionId);

    return {
      success: true,
      chain: chain,
      message: `Found ${chain.ancestors.length} ancestors and ${chain.successors.length} successors`
    };
  }

  /**
   * Capture research findings in real-time
   * @param {Object} research - Research data from exploration/investigation
   * @returns {Object} Captured research with metadata
   */
  captureResearch(research) {
    const timestamp = new Date().toISOString();

    const captured = {
      id: this.generateRealtimeId('res'),
      type: 'research',
      timestamp: timestamp,
      title: research.title || research.finding,
      summary: research.finding || research.summary,
      content: {
        finding: research.finding,
        context: research.context,
        sources: research.sources || [],
        evidence: research.evidence || null,
        applicability: research.applicability || null,
        limitations: research.limitations || [],
        followUp: research.followUp || [],
        verified: research.verified || false
      },
      context: {
        trackId: research.trackId,
        taskId: research.taskId,
        phase: research.phase,
        agentId: research.agentId,
        branch: research.branch
      },
      domain: research.domain || this.inferDomainFromText(research.finding),
      tags: research.tags || this.extractTagsFromText(research.finding),
      confidence: research.confidence || 0.6,
      importance: research.importance || 'normal',
      metadata: {
        createdAt: timestamp,
        source: 'exploration',
        searchTerms: research.searchTerms || []
      }
    };

    return {
      success: true,
      research: captured,
      message: `Research captured: ${captured.title}`
    };
  }

  /**
   * Extract learnings from a completed phase
   * @param {Object} phase - Completed phase data
   * @param {Object} track - Track context
   * @returns {Object} Extracted phase learnings
   */
  extractPhaseLearnings(phase, track) {
    const learnings = {
      phaseNumber: phase.number || phase.id,
      phaseName: phase.name || phase.title,
      trackId: track.id,
      extractedAt: new Date().toISOString(),
      decisions: [],
      patterns: [],
      insights: [],
      blockers: []
    };

    // Extract decisions from phase tasks
    if (phase.tasks) {
      for (const task of phase.tasks) {
        if (task.decisions && task.decisions.length > 0) {
          learnings.decisions.push(...task.decisions);
        }

        // Look for decision indicators in task notes
        if (task.notes) {
          const extractedDecisions = this.extractDecisionsFromNotes(task.notes, task);
          learnings.decisions.push(...extractedDecisions);
        }
      }
    }

    // Extract patterns from implementation approach
    if (phase.implementation) {
      const patterns = this.detectPatternsInPhase(phase);
      learnings.patterns.push(...patterns);
    }

    // Extract insights from phase completion
    if (phase.summary || phase.notes) {
      const insights = this.extractInsightsFromText(phase.summary || phase.notes);
      learnings.insights.push(...insights);
    }

    // Collect blocker resolutions
    if (phase.blockers) {
      learnings.blockers = phase.blockers.map(b => ({
        issue: b.issue || b.description,
        resolution: b.resolution,
        preventionStrategy: b.preventionStrategy || null,
        timeSpent: b.timeSpent || null
      }));
    }

    // Generate phase learning summary
    learnings.summary = {
      decisionsCount: learnings.decisions.length,
      patternsCount: learnings.patterns.length,
      insightsCount: learnings.insights.length,
      blockersResolved: learnings.blockers.filter(b => b.resolution).length,
      keyLearnings: this.extractKeyLearnings(learnings)
    };

    return {
      success: true,
      learnings: learnings,
      message: `Extracted ${learnings.summary.decisionsCount} decisions, ${learnings.summary.patternsCount} patterns from phase ${learnings.phaseNumber}`
    };
  }

  /**
   * Create retrospective with journal data
   * @param {Object} track - Completed track
   * @param {Object} journalData - Session journal data
   * @param {Object} feedback - Optional user feedback
   * @returns {Object} Enhanced retrospective
   */
  createRetrospectiveWithJournal(track, journalData, feedback = {}) {
    // Create base retrospective
    const baseRetro = this.createRetrospective(track, feedback);

    // Enhance with journal data
    if (journalData && journalData.entries) {
      // Add journal-sourced decisions
      const journalDecisions = journalData.entries
        .filter(e => e.type === 'decision')
        .map(e => e.summary || e.title);

      if (!baseRetro.retrospective.decisions) {
        baseRetro.retrospective.decisions = [];
      }
      baseRetro.retrospective.decisions.push(...journalDecisions);

      // Add journal-sourced discoveries
      const discoveries = journalData.entries
        .filter(e => e.type === 'discovery')
        .map(e => e.summary || e.insight);

      baseRetro.retrospective.discoveries = discoveries;

      // Add resolved blockers from journal
      const resolvedBlockers = journalData.entries
        .filter(e => e.type === 'blocker' && e.details?.resolved)
        .map(e => ({
          issue: e.summary,
          resolution: e.details.resolution,
          preventionStrategy: e.details.preventionStrategy
        }));

      baseRetro.retrospective.resolvedBlockers = resolvedBlockers;

      // Add journal summary
      baseRetro.retrospective.journalSummary = journalData.summary || {
        entriesCount: journalData.entries.length,
        decisionsCount: journalDecisions.length,
        discoveriesCount: discoveries.length
      };
    }

    // Update markdown content
    baseRetro.content = this.formatEnhancedRetrospectiveMarkdown(baseRetro.retrospective);

    return baseRetro;
  }

  // ============================================
  // Helper Methods for Real-time Capture
  // ============================================

  /**
   * Generate a real-time capture ID
   * @param {string} prefix - ID prefix
   * @returns {string} Unique ID
   */
  generateRealtimeId(prefix) {
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substr(2, 6);
    return `${prefix}_${timestamp}_${random}`;
  }

  /**
   * Infer domain from decision content
   * @param {Object} decision - Decision data
   * @returns {string|null} Inferred domain
   */
  inferDomainFromDecision(decision) {
    const text = `${decision.title || ''} ${decision.rationale || ''} ${decision.choice || ''}`.toLowerCase();
    return this.inferDomainFromText(text);
  }

  /**
   * Infer domain from text content
   * @param {string} text - Text to analyze
   * @returns {string|null} Inferred domain
   */
  inferDomainFromText(text) {
    const normalizedText = (text || '').toLowerCase();

    const domainPatterns = {
      frontend: /\b(react|vue|angular|component|css|html|ui|ux|button|form|modal|style)\b/,
      backend: /\b(api|endpoint|server|controller|route|middleware|service|handler)\b/,
      database: /\b(sql|query|table|migration|schema|index|database|postgres|mysql|mongo)\b/,
      security: /\b(auth|permission|token|jwt|csrf|xss|injection|encrypt|secure|password)\b/,
      testing: /\b(test|spec|jest|mocha|coverage|mock|fixture|assertion|unit|integration)\b/,
      devops: /\b(deploy|docker|kubernetes|ci|cd|pipeline|aws|azure|gcp|terraform)\b/,
      performance: /\b(optimize|cache|latency|throughput|memory|cpu|performance|speed)\b/,
      architecture: /\b(architecture|design|pattern|structure|module|layer|service)\b/
    };

    for (const [domain, pattern] of Object.entries(domainPatterns)) {
      if (pattern.test(normalizedText)) {
        return domain;
      }
    }

    return null;
  }

  /**
   * Extract tags from decision content
   * @param {Object} decision - Decision data
   * @returns {Array} Extracted tags
   */
  extractTagsFromDecision(decision) {
    const text = `${decision.title || ''} ${decision.choice || ''} ${decision.rationale || ''}`;
    return this.extractTagsFromText(text);
  }

  /**
   * Extract tags from text content
   * @param {string} text - Text to analyze
   * @returns {Array} Extracted tags
   */
  extractTagsFromText(text) {
    const normalizedText = (text || '').toLowerCase();
    const tags = [];

    // Technology tags
    const techPatterns = /\b(react|vue|angular|node|python|java|typescript|javascript|graphql|rest|postgres|mongodb|redis|docker|kubernetes)\b/gi;
    const techMatches = normalizedText.match(techPatterns) || [];
    tags.push(...techMatches.map(t => t.toLowerCase()));

    // Action tags
    const actionPatterns = /\b(create|update|delete|fix|add|remove|implement|refactor|optimize|migrate)\b/gi;
    const actionMatches = normalizedText.match(actionPatterns) || [];
    tags.push(...actionMatches.map(a => a.toLowerCase()));

    // Concept tags
    const conceptPatterns = /\b(authentication|authorization|caching|logging|monitoring|validation|error-handling)\b/gi;
    const conceptMatches = normalizedText.match(conceptPatterns) || [];
    tags.push(...conceptMatches.map(c => c.toLowerCase()));

    return [...new Set(tags)];
  }

  /**
   * Extract decisions from task notes
   * @param {string} notes - Task notes
   * @param {Object} task - Task context
   * @returns {Array} Extracted decisions
   */
  extractDecisionsFromNotes(notes, task) {
    const decisions = [];
    const decisionIndicators = [
      /decided to/gi,
      /chose to/gi,
      /will use/gi,
      /going with/gi,
      /selected/gi,
      /prefer(red)?/gi
    ];

    const sentences = notes.split(/[.!?]+/);

    for (const sentence of sentences) {
      for (const pattern of decisionIndicators) {
        if (pattern.test(sentence)) {
          decisions.push({
            summary: sentence.trim(),
            source: 'task_notes',
            taskId: task.id,
            confidence: 0.5, // Lower confidence for auto-extracted
            autoExtracted: true
          });
          break; // Only match once per sentence
        }
      }
    }

    return decisions;
  }

  /**
   * Detect patterns in phase implementation
   * @param {Object} phase - Phase data
   * @returns {Array} Detected patterns
   */
  detectPatternsInPhase(phase) {
    const patterns = [];

    // Look for repeated structures
    if (phase.tasks && phase.tasks.length > 2) {
      const taskTypes = phase.tasks.map(t => t.type || 'unknown');
      const typeCounts = {};

      for (const type of taskTypes) {
        typeCounts[type] = (typeCounts[type] || 0) + 1;
      }

      // If a type appears 3+ times, it might be a pattern
      for (const [type, count] of Object.entries(typeCounts)) {
        if (count >= 3) {
          patterns.push({
            name: `Repeated ${type} pattern`,
            category: 'implementation',
            occurrences: count,
            confidence: 0.6
          });
        }
      }
    }

    return patterns;
  }

  /**
   * Extract insights from text
   * @param {string} text - Text to analyze
   * @returns {Array} Extracted insights
   */
  extractInsightsFromText(text) {
    const insights = [];
    const insightIndicators = [
      /learned that/gi,
      /discovered that/gi,
      /realized that/gi,
      /found that/gi,
      /noticed that/gi,
      /important to/gi,
      /should always/gi,
      /never forget/gi
    ];

    const sentences = (text || '').split(/[.!?]+/);

    for (const sentence of sentences) {
      for (const pattern of insightIndicators) {
        if (pattern.test(sentence)) {
          insights.push({
            insight: sentence.trim(),
            confidence: 0.5,
            autoExtracted: true
          });
          break;
        }
      }
    }

    return insights;
  }

  /**
   * Extract key learnings from phase learnings
   * @param {Object} learnings - Phase learnings object
   * @returns {Array} Key learnings (top 3)
   */
  extractKeyLearnings(learnings) {
    const all = [
      ...learnings.decisions.map(d => ({ type: 'decision', text: d.summary || d.title, confidence: d.confidence || 0.5 })),
      ...learnings.insights.map(i => ({ type: 'insight', text: i.insight, confidence: i.confidence || 0.5 })),
      ...learnings.blockers.filter(b => b.resolution).map(b => ({ type: 'blocker_resolution', text: `${b.issue} → ${b.resolution}`, confidence: 0.8 }))
    ];

    // Sort by confidence and take top 3
    return all
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 3)
      .map(l => l.text);
  }

  // ============================================
  // Entity and TODO Capture Methods
  // ============================================

  /**
   * Capture an entity (component, service, module, etc.)
   * @param {Object} entity - Entity data
   * @returns {Object} Captured entity with metadata
   */
  captureEntity(entity) {
    const timestamp = new Date().toISOString();

    const captured = {
      id: this.generateRealtimeId('ent'),
      type: 'entity',
      timestamp: timestamp,
      title: entity.name || entity.title,
      name: entity.name || entity.title,
      entityType: entity.entityType || 'component', // service|component|module|api|database
      content: {
        description: entity.description,
        location: entity.location,
        responsibilities: entity.responsibilities || [],
        dependencies: entity.dependencies || [],
        interfaces: entity.interfaces || [],
        notes: entity.notes || null
      },
      context: {
        trackId: entity.trackId,
        taskId: entity.taskId,
        branch: entity.branch
      },
      domain: entity.domain || this.inferDomainFromText(entity.description || ''),
      tags: entity.tags || this.extractTagsFromText(`${entity.name} ${entity.description || ''}`),
      relatedDecisions: entity.relatedDecisions || [],
      relatedPatterns: entity.relatedPatterns || [],
      confidence: entity.confidence || 0.8,
      metadata: {
        createdAt: timestamp,
        updatedAt: timestamp,
        source: entity.source || 'manual',
        autoExtracted: entity.autoExtracted || false
      }
    };

    return {
      success: true,
      entity: captured,
      message: `Entity captured: ${captured.name} (${captured.entityType})`
    };
  }

  /**
   * Capture a TODO item for future work
   * @param {Object} todo - TODO data
   * @returns {Object} Captured TODO with metadata
   */
  captureTodo(todo) {
    const timestamp = new Date().toISOString();

    const captured = {
      id: this.generateRealtimeId('todo'),
      type: 'todo',
      timestamp: timestamp,
      title: todo.title,
      priority: todo.priority || 'medium', // high|medium|low
      status: todo.status || 'pending', // pending|in-progress|done|wont-do
      content: {
        description: todo.description,
        acceptanceCriteria: todo.acceptanceCriteria || [],
        notes: todo.notes || null,
        blockedBy: todo.blockedBy || null,
        estimatedEffort: todo.estimatedEffort || null
      },
      context: {
        trackId: todo.trackId || todo.relatedTrack,
        taskId: todo.taskId,
        sessionId: todo.sessionId || todo.createdFrom,
        branch: todo.branch
      },
      dueDate: todo.dueDate || null,
      domain: todo.domain || this.inferDomainFromText(todo.title + ' ' + (todo.description || '')),
      tags: todo.tags || this.extractTagsFromText(todo.title + ' ' + (todo.description || '')),
      assignee: todo.assignee || null,
      confidence: 1.0, // TODOs are explicit, high confidence
      metadata: {
        createdAt: timestamp,
        updatedAt: timestamp,
        source: todo.source || 'manual',
        completedAt: todo.status === 'done' ? timestamp : null
      }
    };

    return {
      success: true,
      todo: captured,
      message: `TODO captured: ${captured.title} [${captured.priority}]`
    };
  }

  /**
   * Update a TODO status
   * @param {Object} todo - Existing TODO entry
   * @param {string} newStatus - New status
   * @param {Object} updates - Additional updates
   * @returns {Object} Updated TODO
   */
  updateTodoStatus(todo, newStatus, updates = {}) {
    const timestamp = new Date().toISOString();

    const updated = {
      ...todo,
      status: newStatus,
      content: {
        ...todo.content,
        ...updates.content
      },
      metadata: {
        ...todo.metadata,
        updatedAt: timestamp,
        completedAt: newStatus === 'done' ? timestamp : todo.metadata?.completedAt
      }
    };

    if (updates.notes) {
      updated.content.notes = updated.content.notes
        ? `${updated.content.notes}\n\n${timestamp}: ${updates.notes}`
        : `${timestamp}: ${updates.notes}`;
    }

    return {
      success: true,
      todo: updated,
      message: `TODO updated: ${updated.title} → ${newStatus}`
    };
  }

  /**
   * Extract entities from code analysis
   * @param {Object} codeAnalysis - Code analysis result
   * @returns {Array} Extracted entities
   */
  extractEntitiesFromCode(codeAnalysis) {
    const entities = [];

    // Extract services
    if (codeAnalysis.services) {
      for (const service of codeAnalysis.services) {
        entities.push(this.captureEntity({
          name: service.name,
          entityType: 'service',
          description: service.description || `Service: ${service.name}`,
          location: service.path,
          responsibilities: service.methods || [],
          dependencies: service.imports || [],
          autoExtracted: true
        }).entity);
      }
    }

    // Extract components
    if (codeAnalysis.components) {
      for (const component of codeAnalysis.components) {
        entities.push(this.captureEntity({
          name: component.name,
          entityType: 'component',
          description: component.description || `Component: ${component.name}`,
          location: component.path,
          responsibilities: component.props || [],
          dependencies: component.imports || [],
          autoExtracted: true
        }).entity);
      }
    }

    // Extract API endpoints
    if (codeAnalysis.endpoints) {
      for (const endpoint of codeAnalysis.endpoints) {
        entities.push(this.captureEntity({
          name: `${endpoint.method} ${endpoint.path}`,
          entityType: 'api',
          description: endpoint.description || `API endpoint: ${endpoint.method} ${endpoint.path}`,
          location: endpoint.handler,
          interfaces: [{ method: endpoint.method, path: endpoint.path, params: endpoint.params }],
          autoExtracted: true
        }).entity);
      }
    }

    return entities;
  }

  /**
   * Extract TODOs from code comments
   * @param {string} code - Source code
   * @param {Object} context - Context (file path, etc.)
   * @returns {Array} Extracted TODOs
   */
  extractTodosFromCode(code, context = {}) {
    const todos = [];
    const todoPatterns = [
      /\/\/\s*TODO:?\s*(.+)/gi,
      /\/\*\s*TODO:?\s*(.+?)\*\//gi,
      /#\s*TODO:?\s*(.+)/gi,
      /<!--\s*TODO:?\s*(.+?)-->/gi
    ];

    for (const pattern of todoPatterns) {
      let match;
      while ((match = pattern.exec(code)) !== null) {
        const title = match[1].trim();

        // Skip if too short or looks like template
        if (title.length < 5 || title.includes('{{') || title.includes('$')) {
          continue;
        }

        // Infer priority from keywords
        let priority = 'medium';
        if (/urgent|critical|asap|important/i.test(title)) {
          priority = 'high';
        } else if (/maybe|eventually|nice.?to.?have|low/i.test(title)) {
          priority = 'low';
        }

        todos.push(this.captureTodo({
          title: title,
          priority: priority,
          source: 'code-comment',
          location: context.filePath,
          trackId: context.trackId,
          autoExtracted: true
        }).todo);
      }
    }

    return todos;
  }

  /**
   * Format enhanced retrospective with journal data
   * @param {Object} retro - Enhanced retrospective object
   * @returns {string} Formatted markdown
   */
  formatEnhancedRetrospectiveMarkdown(retro) {
    let content = this.formatRetrospectiveMarkdown(retro);

    // Add journal-specific sections
    if (retro.decisions && retro.decisions.length > 0) {
      content += `\n## Key Decisions Made\n\n`;
      for (const decision of retro.decisions.slice(0, 5)) {
        content += `- ${decision}\n`;
      }
    }

    if (retro.discoveries && retro.discoveries.length > 0) {
      content += `\n## Discoveries\n\n`;
      for (const discovery of retro.discoveries.slice(0, 5)) {
        content += `- ${discovery}\n`;
      }
    }

    if (retro.resolvedBlockers && retro.resolvedBlockers.length > 0) {
      content += `\n## Blocker Resolutions\n\n`;
      for (const blocker of retro.resolvedBlockers) {
        content += `### ${blocker.issue}\n`;
        content += `- **Resolution**: ${blocker.resolution}\n`;
        if (blocker.preventionStrategy) {
          content += `- **Prevention**: ${blocker.preventionStrategy}\n`;
        }
        content += '\n';
      }
    }

    if (retro.journalSummary) {
      content += `\n## Session Journal Summary\n\n`;
      content += `- Total Entries: ${retro.journalSummary.entriesCount || 0}\n`;
      content += `- Decisions Captured: ${retro.journalSummary.decisionsCount || 0}\n`;
      content += `- Discoveries Made: ${retro.journalSummary.discoveriesCount || 0}\n`;
    }

    return content;
  }

  // ============================================
  // Enhanced Document Generation Templates
  // ============================================

  /**
   * Generate a Technical Specification document
   * @param {Object} spec - Specification data
   * @returns {Object} Generated specification
   */
  generateTechnicalSpec(spec) {
    const timestamp = new Date().toISOString();

    const markdown = `# Technical Specification: ${spec.title}

**Version**: ${spec.version || '1.0'}
**Status**: ${spec.status || 'Draft'}
**Authors**: ${spec.authors?.join(', ') || 'Development Team'}
**Date**: ${timestamp.split('T')[0]}

## Overview

${spec.overview || spec.description || 'No overview provided.'}

## Goals

${spec.goals?.map((g, i) => `${i + 1}. ${g}`).join('\n') || '- Goals not specified'}

## Non-Goals

${spec.nonGoals?.map((g, i) => `${i + 1}. ${g}`).join('\n') || '- Non-goals not specified'}

## Background

${spec.background || 'No background context provided.'}

## System Design

### Architecture Overview

${spec.architecture?.overview || 'Architecture details not specified.'}

### Components

${this.formatComponentsSection(spec.entities || [])}

### Data Flow

${spec.dataFlow || 'Data flow not documented.'}

## Key Decisions

${this.formatDecisionsSection(spec.decisions || [])}

## API Design

${this.formatAPISection(spec.api || [])}

## Security Considerations

${spec.security?.map(s => `- ${s}`).join('\n') || '- Security considerations not documented'}

## Testing Strategy

${spec.testing || '- Unit tests for all business logic\n- Integration tests for API endpoints\n- E2E tests for critical flows'}

## Rollout Plan

${spec.rollout || 'Rollout plan not specified.'}

## Open Questions

${spec.openQuestions?.map(q => `- [ ] ${q}`).join('\n') || '- No open questions'}

## References

${spec.references?.map(r => `- ${r}`).join('\n') || '- No references'}

---
*Generated from Knowledge System on ${timestamp}*
`;

    return {
      type: 'spec',
      title: spec.title,
      content: markdown,
      filePath: `docs/specs/${this.slugify(spec.title)}.md`,
      generatedAt: timestamp
    };
  }

  /**
   * Generate an Operational Runbook
   * @param {Object} runbook - Runbook data
   * @returns {Object} Generated runbook
   */
  generateRunbook(runbook) {
    const timestamp = new Date().toISOString();

    const markdown = `# Runbook: ${runbook.title}

**Last Updated**: ${timestamp.split('T')[0]}
**Domain**: ${runbook.domain || 'Operations'}
**Owner**: ${runbook.owner || 'Operations Team'}
**On-Call**: ${runbook.onCall || 'See on-call schedule'}

## Overview

${runbook.overview || runbook.description || 'No overview provided.'}

## Prerequisites

${runbook.prerequisites?.map(p => `- [ ] ${p}`).join('\n') || '- No specific prerequisites'}

## Procedures

${this.formatProceduresSection(runbook.procedures || [])}

## Troubleshooting

${this.formatTroubleshootingSection(runbook.troubleshooting || runbook.blockers || [])}

## Monitoring & Alerts

### Key Metrics

${runbook.metrics?.map(m => `- **${m.name}**: ${m.description}`).join('\n') || '- Metrics not specified'}

### Alert Response

${runbook.alerts?.map(a => `
#### Alert: ${a.name}

**Severity**: ${a.severity || 'Medium'}
**Response**: ${a.response}
`).join('\n') || 'Alert responses not documented.'}

## Escalation Path

${runbook.escalation || `
1. First responder (on-call engineer)
2. Team lead
3. Engineering manager
4. VP of Engineering
`}

## Recovery Procedures

### Rollback

${runbook.rollback || `
\`\`\`bash
# Standard rollback procedure
./rollback.sh <environment>
\`\`\`
`}

### Data Recovery

${runbook.dataRecovery || 'Data recovery procedures not documented.'}

## Communication Templates

### Incident Start

${runbook.templates?.incidentStart || `
**Subject**: [INCIDENT] ${runbook.title} - Investigation in Progress

We are investigating an issue with ${runbook.title}.
- **Impact**: TBD
- **ETA**: Investigating
- **Updates**: Every 30 minutes
`}

### Incident Resolution

${runbook.templates?.incidentResolution || `
**Subject**: [RESOLVED] ${runbook.title}

The incident has been resolved.
- **Root Cause**: TBD
- **Resolution**: TBD
- **Duration**: TBD
- **Post-mortem**: Scheduled
`}

## Appendix

### Useful Commands

${runbook.commands?.map(c => `
\`\`\`bash
# ${c.description}
${c.command}
\`\`\`
`).join('\n') || 'No commands documented.'}

### Related Documentation

${runbook.relatedDocs?.map(d => `- [${d.title}](${d.link})`).join('\n') || '- No related documentation'}

---
*Generated from Knowledge System on ${timestamp}*
`;

    return {
      type: 'runbook',
      title: runbook.title,
      content: markdown,
      filePath: `docs/runbooks/${this.slugify(runbook.title)}.md`,
      generatedAt: timestamp
    };
  }

  /**
   * Generate a Development Guide
   * @param {Object} guide - Guide data
   * @returns {Object} Generated guide
   */
  generateDevelopmentGuide(guide) {
    const timestamp = new Date().toISOString();

    const markdown = `# Development Guide: ${guide.title}

**Audience**: ${guide.audience || 'All Developers'}
**Last Updated**: ${timestamp.split('T')[0]}
**Prerequisites**: ${guide.prerequisites?.join(', ') || 'Basic programming knowledge'}

## Introduction

${guide.introduction || guide.description || 'Welcome to this development guide.'}

## Getting Started

### Prerequisites

${guide.setup?.prerequisites?.map(p => `- ${p}`).join('\n') || '- Node.js 18+\n- npm or yarn\n- Git'}

### Installation

${guide.setup?.installation || `
\`\`\`bash
# Clone the repository
git clone <repository-url>

# Install dependencies
npm install

# Start development server
npm run dev
\`\`\`
`}

### Project Structure

${guide.structure || `
\`\`\`
src/
├── components/    # Reusable UI components
├── services/      # Business logic and API calls
├── utils/         # Utility functions
├── types/         # TypeScript type definitions
└── tests/         # Test files
\`\`\`
`}

## Key Concepts

${this.formatConceptsSection(guide.concepts || [])}

## Architecture

### Overview

${guide.architecture?.overview || 'Architecture overview not provided.'}

### Key Components

${this.formatGuideComponentsSection(guide.entities || [])}

## Patterns & Best Practices

${this.formatPatternsGuideSection(guide.patterns || [])}

## Common Tasks

${this.formatTasksSection(guide.tasks || [])}

## Testing

### Running Tests

${guide.testing?.running || `
\`\`\`bash
# Run all tests
npm test

# Run with coverage
npm test -- --coverage

# Run specific test
npm test -- path/to/test.spec.ts
\`\`\`
`}

### Writing Tests

${guide.testing?.writing || 'Test writing guidelines not specified.'}

## Debugging

### Common Issues

${guide.debugging?.issues?.map(i => `
#### ${i.issue}

**Symptoms**: ${i.symptoms}
**Solution**: ${i.solution}
`).join('\n') || 'No common issues documented.'}

### Debugging Tools

${guide.debugging?.tools?.map(t => `- **${t.name}**: ${t.description}`).join('\n') || '- Browser DevTools\n- VS Code debugger'}

## Contributing

${guide.contributing || `
1. Create a feature branch from \`main\`
2. Make your changes
3. Write/update tests
4. Submit a pull request
5. Address review feedback
`}

## FAQ

${guide.faq?.map(q => `
### ${q.question}

${q.answer}
`).join('\n') || 'No FAQ items yet.'}

## Resources

${guide.resources?.map(r => `- [${r.title}](${r.link}) - ${r.description || ''}`).join('\n') || '- No additional resources'}

---
*Generated from Knowledge System on ${timestamp}*
`;

    return {
      type: 'guide',
      title: guide.title,
      content: markdown,
      filePath: `docs/guides/${this.slugify(guide.title)}.md`,
      generatedAt: timestamp
    };
  }

  /**
   * Generate a Changelog from decisions
   * @param {Array} decisions - Decision entries
   * @param {Object} options - Generation options
   * @returns {Object} Generated changelog
   */
  generateChangelog(decisions, options = {}) {
    const timestamp = new Date().toISOString();

    // Group decisions by date (month)
    const grouped = {};
    for (const decision of decisions) {
      const date = new Date(decision.metadata?.createdAt || decision.timestamp);
      const monthKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
      if (!grouped[monthKey]) {
        grouped[monthKey] = [];
      }
      grouped[monthKey].push(decision);
    }

    // Sort months descending
    const sortedMonths = Object.keys(grouped).sort().reverse();

    let content = `# Changelog

> Generated from Knowledge System decisions
> Last updated: ${timestamp.split('T')[0]}

`;

    for (const monthKey of sortedMonths) {
      const [year, month] = monthKey.split('-');
      const monthName = new Date(year, parseInt(month) - 1).toLocaleString('default', { month: 'long' });

      content += `## ${monthName} ${year}\n\n`;

      for (const decision of grouped[monthKey]) {
        const date = new Date(decision.metadata?.createdAt || decision.timestamp);
        const dateStr = date.toISOString().split('T')[0];
        const domain = decision.domain ? `[${decision.domain}]` : '';

        content += `### ${dateStr} ${domain}\n\n`;
        content += `**${decision.title}**\n\n`;

        if (decision.content?.choice || decision.content?.decision) {
          content += `${decision.content.choice || decision.content.decision}\n\n`;
        }

        if (decision.content?.rationale) {
          content += `*Rationale*: ${decision.content.rationale}\n\n`;
        }

        content += `---\n\n`;
      }
    }

    content += `\n*Generated from Knowledge System*`;

    return {
      type: 'changelog',
      title: 'Changelog',
      content: content,
      filePath: options.output || 'CHANGELOG.md',
      generatedAt: timestamp,
      decisionsIncluded: decisions.length
    };
  }

  // ============================================
  // Helper Methods for Document Generation
  // ============================================

  /**
   * Format components section for spec
   */
  formatComponentsSection(entities) {
    if (!entities || entities.length === 0) {
      return 'Components not specified.';
    }

    return entities.map(entity => `
#### ${entity.title || entity.name}

- **Type**: ${entity.entityType || 'Component'}
- **Location**: \`${entity.content?.location || entity.location || 'N/A'}\`
- **Description**: ${entity.content?.description || entity.description || 'No description'}
${entity.content?.responsibilities?.length ? `- **Responsibilities**:\n${entity.content.responsibilities.map(r => `  - ${r}`).join('\n')}` : ''}
${entity.content?.dependencies?.length ? `- **Dependencies**: ${entity.content.dependencies.join(', ')}` : ''}
`).join('\n');
  }

  /**
   * Format decisions section for spec
   */
  formatDecisionsSection(decisions) {
    if (!decisions || decisions.length === 0) {
      return 'No key decisions documented.';
    }

    return decisions.map(d => `
### ${d.id || 'Decision'}: ${d.title}

${d.content?.choice || d.content?.decision || d.summary || 'Decision details not available.'}

${d.content?.rationale ? `*Rationale*: ${d.content.rationale}` : ''}
`).join('\n');
  }

  /**
   * Format API section for spec
   */
  formatAPISection(endpoints) {
    if (!endpoints || endpoints.length === 0) {
      return 'API not specified.';
    }

    let content = '| Endpoint | Method | Description |\n|----------|--------|-------------|\n';

    for (const ep of endpoints) {
      content += `| ${ep.path} | ${ep.method} | ${ep.description || 'N/A'} |\n`;
    }

    return content;
  }

  /**
   * Format procedures section for runbook
   */
  formatProceduresSection(procedures) {
    if (!procedures || procedures.length === 0) {
      return 'No procedures documented.';
    }

    return procedures.map(proc => `
### ${proc.title || proc.name}

${proc.description || ''}

#### Prerequisites

${proc.prerequisites?.map(p => `- [ ] ${p}`).join('\n') || '- None'}

#### Steps

${proc.steps?.map((s, i) => `${i + 1}. ${s}`).join('\n') || 'Steps not documented.'}

${proc.verification ? `
#### Verification

${proc.verification}
` : ''}
`).join('\n');
  }

  /**
   * Format troubleshooting section for runbook
   */
  formatTroubleshootingSection(blockers) {
    if (!blockers || blockers.length === 0) {
      return 'No troubleshooting entries.';
    }

    return blockers.map(b => `
### Issue: ${b.title || b.content?.issue || b.issue || 'Unknown Issue'}

**Symptoms**: ${b.content?.symptoms || b.symptoms || 'N/A'}

**Resolution**:
${b.content?.resolution || b.resolution || 'Resolution not documented.'}

${b.content?.preventionStrategy ? `**Prevention**: ${b.content.preventionStrategy}` : ''}

*ID: ${b.id}*
`).join('\n');
  }

  /**
   * Format concepts section for guide
   */
  formatConceptsSection(concepts) {
    if (!concepts || concepts.length === 0) {
      return 'Key concepts not documented.';
    }

    return concepts.map(c => `
### ${c.name || c.title}

${c.description || c.explanation || 'Description not available.'}

${c.example ? `
**Example**:
\`\`\`
${c.example}
\`\`\`
` : ''}
`).join('\n');
  }

  /**
   * Format guide components section
   */
  formatGuideComponentsSection(entities) {
    if (!entities || entities.length === 0) {
      return 'No key components documented.';
    }

    return entities.map(e => `
#### ${e.title || e.name}

${e.content?.description || e.description || 'No description.'}

- **Location**: \`${e.content?.location || e.location || 'N/A'}\`
- **Type**: ${e.entityType || 'Component'}
`).join('\n');
  }

  /**
   * Format patterns section for guide
   */
  formatPatternsGuideSection(patterns) {
    if (!patterns || patterns.length === 0) {
      return 'No patterns documented.';
    }

    return patterns.map(p => `
### ${p.title || p.name}

**When to use**: ${p.content?.problem || p.problem || 'N/A'}

**How it works**: ${p.content?.solution || p.solution || 'N/A'}

${p.content?.codeExample || p.codeExample ? `
**Example**:
\`\`\`
${p.content?.codeExample || p.codeExample}
\`\`\`
` : ''}

${p.content?.tradeoffs?.length ? `
**Trade-offs**:
${p.content.tradeoffs.map(t => `- ${typeof t === 'string' ? t : `**${t.aspect}**: ${t.description}`}`).join('\n')}
` : ''}
`).join('\n');
  }

  /**
   * Format common tasks section for guide
   */
  formatTasksSection(tasks) {
    if (!tasks || tasks.length === 0) {
      return `
### Adding a New Feature

1. Create feature branch
2. Implement the feature
3. Write tests
4. Submit PR

### Fixing a Bug

1. Create bug fix branch
2. Write failing test
3. Fix the bug
4. Verify test passes
5. Submit PR
`;
    }

    return tasks.map(t => `
### ${t.title || t.name}

${t.description || ''}

${t.steps?.map((s, i) => `${i + 1}. ${s}`).join('\n') || ''}

${t.example ? `
**Example**:
\`\`\`
${t.example}
\`\`\`
` : ''}
`).join('\n');
  }

  /**
   * Convert string to URL-friendly slug
   */
  slugify(text) {
    return (text || 'untitled')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50);
  }
}

module.exports = KnowledgeCapture;
