/**
 * Knowledge Capture Skill
 *
 * Captures decisions, patterns, and learnings from development work.
 * Generates ADRs, maintains pattern library, and supports retrospectives.
 */

class KnowledgeCapture {
  constructor(config = {}) {
    this.config = {
      decisionsDir: config.decisionsDir || 'maestro/decisions',
      patternsDir: config.patternsDir || 'maestro/patterns',
      retrospectivesDir: config.retrospectivesDir || 'maestro/retrospectives',
      autoCapture: config.autoCapture !== false,
      ...config
    };

    this.decisions = [];
    this.patterns = [];
  }

  /**
   * Create an Architecture Decision Record
   * @param {Object} decision - Decision details
   * @returns {Object} Created ADR
   */
  createADR(decision) {
    const adrId = this.generateADRId();
    const timestamp = new Date().toISOString();

    const adr = {
      id: adrId,
      title: decision.title,
      status: decision.status || 'proposed', // proposed, accepted, deprecated, superseded
      date: timestamp,
      context: decision.context,
      decision: decision.decision,
      consequences: decision.consequences || [],
      alternatives: decision.alternatives || [],
      relatedTracks: decision.trackIds || [],
      participants: decision.participants || [],
      supersedes: decision.supersedes || null,
      supersededBy: null,
      tags: decision.tags || [],
      metadata: {
        createdAt: timestamp,
        updatedAt: timestamp,
        autoGenerated: decision.autoGenerated || false
      }
    };

    this.decisions.push(adr);

    return {
      adr,
      filePath: `${this.config.decisionsDir}/${adrId}.md`,
      content: this.formatADRMarkdown(adr)
    };
  }

  /**
   * Auto-generate ADR from conversation analysis
   * @param {Object} conversation - Analyzed conversation
   * @returns {Object|null} Generated ADR or null
   */
  autoGenerateADR(conversation) {
    // Check if conversation contains a significant decision
    if (!this.isSignificantDecision(conversation)) {
      return null;
    }

    const extracted = {
      title: this.extractDecisionTitle(conversation),
      context: this.extractContext(conversation),
      decision: this.extractDecision(conversation),
      alternatives: this.extractAlternatives(conversation),
      consequences: this.extractConsequences(conversation),
      trackIds: conversation.relatedTracks || [],
      autoGenerated: true,
      tags: this.extractTags(conversation)
    };

    return this.createADR(extracted);
  }

  /**
   * Record a reusable pattern from implementation
   * @param {Object} pattern - Pattern details
   * @returns {Object} Created pattern
   */
  recordPattern(pattern) {
    const patternId = this.generatePatternId(pattern.name);
    const timestamp = new Date().toISOString();

    const record = {
      id: patternId,
      name: pattern.name,
      category: pattern.category, // architectural, design, implementation, testing
      description: pattern.description,
      problem: pattern.problem,
      solution: pattern.solution,
      codeExample: pattern.codeExample || null,
      useCases: pattern.useCases || [],
      tradeoffs: pattern.tradeoffs || [],
      relatedPatterns: pattern.relatedPatterns || [],
      sourceTrack: pattern.trackId || null,
      tags: pattern.tags || [],
      metadata: {
        createdAt: timestamp,
        usageCount: 0,
        lastUsed: null
      }
    };

    this.patterns.push(record);

    return {
      pattern: record,
      filePath: `${this.config.patternsDir}/${patternId}.md`,
      content: this.formatPatternMarkdown(record)
    };
  }

  /**
   * Extract patterns from completed track
   * @param {Object} track - Completed track data
   * @returns {Array} Extracted patterns
   */
  extractPatternsFromTrack(track) {
    const patterns = [];

    // Analyze implementation approach
    if (track.plan && track.plan.phases) {
      for (const phase of track.plan.phases) {
        const phasePattern = this.analyzePhaseForPatterns(phase);
        if (phasePattern) {
          patterns.push(phasePattern);
        }
      }
    }

    // Analyze code changes for common patterns
    if (track.commits) {
      const codePatterns = this.analyzeCommitsForPatterns(track.commits);
      patterns.push(...codePatterns);
    }

    return patterns;
  }

  /**
   * Create track retrospective
   * @param {Object} track - Completed track
   * @param {Object} feedback - Retrospective feedback
   * @returns {Object} Retrospective document
   */
  createRetrospective(track, feedback = {}) {
    const retroId = `retro-${track.id}`;
    const timestamp = new Date().toISOString();

    const retrospective = {
      id: retroId,
      trackId: track.id,
      trackTitle: track.title,
      completedAt: timestamp,
      duration: this.calculateTrackDuration(track),
      summary: {
        phasesCompleted: track.phases?.completed || 0,
        tasksCompleted: track.tasks?.completed || 0,
        totalCommits: track.commits?.length || 0
      },
      whatWentWell: feedback.whatWentWell || [],
      whatCouldImprove: feedback.whatCouldImprove || [],
      actionItems: feedback.actionItems || [],
      lessonsLearned: feedback.lessonsLearned || [],
      agentPerformance: this.summarizeAgentPerformance(track),
      metrics: {
        estimatedComplexity: track.plan?.complexity || 'unknown',
        actualDuration: this.calculateTrackDuration(track),
        iterationCount: this.countIterations(track),
        qualityGatesPassed: feedback.qualityGatesPassed || true
      },
      recommendations: this.generateRetrospectiveRecommendations(track, feedback)
    };

    return {
      retrospective,
      filePath: `${this.config.retrospectivesDir}/${retroId}.md`,
      content: this.formatRetrospectiveMarkdown(retrospective)
    };
  }

  /**
   * Generate retrospective prompts for track completion
   * @param {Object} track - Completed track
   * @returns {Array} Prompts for user reflection
   */
  generateRetrospectivePrompts(track) {
    const prompts = [
      {
        id: 'went_well',
        question: 'What went well during this track implementation?',
        category: 'positive',
        suggestions: [
          'Good agent collaboration',
          'Clear requirements',
          'Smooth phase transitions',
          'Effective testing'
        ]
      },
      {
        id: 'could_improve',
        question: 'What could have been improved?',
        category: 'improvement',
        suggestions: [
          'Requirements clarity',
          'Estimation accuracy',
          'Agent selection',
          'Testing coverage'
        ]
      },
      {
        id: 'lessons',
        question: 'What key lessons were learned?',
        category: 'learning',
        suggestions: []
      },
      {
        id: 'actions',
        question: 'What action items should we take forward?',
        category: 'action',
        suggestions: [
          'Update coding standards',
          'Add to pattern library',
          'Create documentation',
          'Refine workflow'
        ]
      }
    ];

    // Add track-specific prompts
    if (track.blockers && track.blockers.length > 0) {
      prompts.push({
        id: 'blockers_resolution',
        question: 'How were blockers resolved? Any prevention strategies?',
        category: 'improvement',
        context: track.blockers
      });
    }

    return prompts;
  }

  /**
   * Search patterns by criteria
   * @param {Object} query - Search criteria
   * @returns {Array} Matching patterns
   */
  searchPatterns(query) {
    let results = [...this.patterns];

    if (query.category) {
      results = results.filter(p => p.category === query.category);
    }

    if (query.tags && query.tags.length > 0) {
      results = results.filter(p =>
        query.tags.some(tag => p.tags.includes(tag))
      );
    }

    if (query.keyword) {
      const keyword = query.keyword.toLowerCase();
      results = results.filter(p =>
        p.name.toLowerCase().includes(keyword) ||
        p.description.toLowerCase().includes(keyword) ||
        p.problem.toLowerCase().includes(keyword)
      );
    }

    return results.sort((a, b) =>
      b.metadata.usageCount - a.metadata.usageCount
    );
  }

  /**
   * Find relevant decisions for a track
   * @param {Object} track - Track to find decisions for
   * @returns {Array} Related decisions
   */
  findRelatedDecisions(track) {
    return this.decisions.filter(d =>
      d.relatedTracks.includes(track.id) ||
      d.tags.some(tag => track.tags?.includes(tag))
    );
  }

  // Format methods
  formatADRMarkdown(adr) {
    return `# ADR-${adr.id}: ${adr.title}

**Status**: ${adr.status}
**Date**: ${adr.date}
**Tags**: ${adr.tags.join(', ') || 'none'}

## Context

${adr.context}

## Decision

${adr.decision}

## Alternatives Considered

${adr.alternatives.map((alt, i) => `${i + 1}. **${alt.title}**: ${alt.description}
   - Pros: ${alt.pros?.join(', ') || 'N/A'}
   - Cons: ${alt.cons?.join(', ') || 'N/A'}`).join('\n\n') || 'None documented'}

## Consequences

### Positive
${adr.consequences.filter(c => c.type === 'positive').map(c => `- ${c.description}`).join('\n') || '- None documented'}

### Negative
${adr.consequences.filter(c => c.type === 'negative').map(c => `- ${c.description}`).join('\n') || '- None documented'}

### Neutral
${adr.consequences.filter(c => c.type === 'neutral').map(c => `- ${c.description}`).join('\n') || '- None documented'}

## Related

- **Tracks**: ${adr.relatedTracks.join(', ') || 'None'}
- **Supersedes**: ${adr.supersedes || 'None'}
- **Participants**: ${adr.participants.join(', ') || 'Not recorded'}

---
*Auto-generated: ${adr.metadata.autoGenerated}*
*Created: ${adr.metadata.createdAt}*
`;
  }

  formatPatternMarkdown(pattern) {
    return `# Pattern: ${pattern.name}

**Category**: ${pattern.category}
**ID**: ${pattern.id}
**Tags**: ${pattern.tags.join(', ') || 'none'}

## Problem

${pattern.problem}

## Solution

${pattern.solution}

${pattern.codeExample ? `## Code Example

\`\`\`
${pattern.codeExample}
\`\`\`` : ''}

## Use Cases

${pattern.useCases.map(uc => `- ${uc}`).join('\n') || 'Not documented'}

## Trade-offs

${pattern.tradeoffs.map(t => `- **${t.aspect}**: ${t.description}`).join('\n') || 'Not documented'}

## Related Patterns

${pattern.relatedPatterns.map(rp => `- ${rp}`).join('\n') || 'None'}

---
*Source Track: ${pattern.sourceTrack || 'N/A'}*
*Usage Count: ${pattern.metadata.usageCount}*
`;
  }

  formatRetrospectiveMarkdown(retro) {
    return `# Retrospective: ${retro.trackTitle}

**Track ID**: ${retro.trackId}
**Completed**: ${retro.completedAt}
**Duration**: ${retro.duration}

## Summary

| Metric | Value |
|--------|-------|
| Phases Completed | ${retro.summary.phasesCompleted} |
| Tasks Completed | ${retro.summary.tasksCompleted} |
| Total Commits | ${retro.summary.totalCommits} |

## What Went Well

${retro.whatWentWell.map(item => `- ${item}`).join('\n') || '- Nothing recorded'}

## What Could Improve

${retro.whatCouldImprove.map(item => `- ${item}`).join('\n') || '- Nothing recorded'}

## Lessons Learned

${retro.lessonsLearned.map(item => `- ${item}`).join('\n') || '- Nothing recorded'}

## Action Items

${retro.actionItems.map((item, i) => `${i + 1}. ${item}`).join('\n') || 'No action items'}

## Agent Performance

${Object.entries(retro.agentPerformance).map(([agent, perf]) =>
    `- **${agent}**: ${perf.tasksCompleted} tasks, ${perf.rating || 'N/A'} rating`
  ).join('\n') || 'Not tracked'}

## Recommendations

${retro.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n') || 'None'}

---
*Generated: ${retro.completedAt}*
`;
  }

  // Helper methods
  generateADRId() {
    const count = this.decisions.length + 1;
    return String(count).padStart(4, '0');
  }

  generatePatternId(name) {
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return `${slug}-${Date.now().toString(36).slice(-4)}`;
  }

  isSignificantDecision(conversation) {
    const keywords = ['decided', 'chose', 'selected', 'will use', 'going with', 'prefer'];
    return keywords.some(kw => conversation.content?.toLowerCase().includes(kw));
  }

  extractDecisionTitle(conversation) {
    return 'Untitled Decision';
  }

  extractContext(conversation) {
    return conversation.context || 'Context not captured';
  }

  extractDecision(conversation) {
    return conversation.decision || 'Decision not captured';
  }

  extractAlternatives(conversation) {
    return [];
  }

  extractConsequences(conversation) {
    return [];
  }

  extractTags(conversation) {
    return [];
  }

  analyzePhaseForPatterns(phase) {
    return null;
  }

  analyzeCommitsForPatterns(commits) {
    return [];
  }

  calculateTrackDuration(track) {
    if (track.created && track.updated) {
      const start = new Date(track.created);
      const end = new Date(track.updated);
      const hours = Math.round((end - start) / (1000 * 60 * 60));
      return hours > 24 ? `${Math.round(hours / 24)} days` : `${hours} hours`;
    }
    return 'Unknown';
  }

  summarizeAgentPerformance(track) {
    const performance = {};
    // Would analyze agent contributions from track data
    return performance;
  }

  countIterations(track) {
    return track.notes?.length || 0;
  }

  generateRetrospectiveRecommendations(track, feedback) {
    const recommendations = [];

    if (feedback.whatCouldImprove?.length > 0) {
      recommendations.push('Address improvement areas in next similar track');
    }

    if (track.blockers?.length > 0) {
      recommendations.push('Document blocker prevention strategies');
    }

    return recommendations;
  }
}

module.exports = KnowledgeCapture;
